version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    command: ["python", "worker.py"]
    depends_on:
      - redis
    volumes:
      - .:/app
