version: "3.8"

services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./job_results:/app/job_results
      - ./uploads:/app/uploads

  worker:
    build: .
    command: python worker.py
    depends_on:
      - redis
    volumes:
      - ./job_results:/app/job_results
      - ./uploads:/app/uploads

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
